### ISSUE TITLE
Unexpected Sign Up Flow

### ISSUE THREAD

**Issue by XERZES27** [YiJeongseop/ToDoLi#1]
Expected Behavior

- Authentication Page should prompt a pop up that allows the user to choose between google accounts when signing in.
- The app prompts this feature only on fresh install, when an account has not been associated with app.

Steps To Reproduce 

- Fresh Install app
- press sign in button
- choose Google account from pop up to sign in with
- accept google drive conditions.
- Logout from account
- pressing the "Sign in with Google" button automatically signs in with previous account without prompting the pop up to choose between Google accounts

**Comment by YiJeongseop** [comment]
Thank you for letting me know the issue! I didn't think about this.

I just fixed it!

The app on the Play Store will be updated later.
