### ISSUE TITLE
Refusing permission to grant access to google drive account. shows unending CircularProgressIndicator.

### ISSUE THREAD

**Issue by XERZES27** [YiJeongseop/ToDoLi#2]
Expected Behavior

- Refusing permission to grant access to the user's google drive account should return the app to the Authentication Page.

Steps To Reproduce

- Fresh Install app
- press sign in button
- choose Google account from pop up to sign in with (if the chosen account has not been previously associated with the app, this will prompt a pop up request permission to grant access to the accounts google drive)
- Press the "Cancel" button.
- The pop up closes, showing a circular progress indicator that never ends.

**Comment by YiJeongseop** [comment]
Thank you for your time and kind! 

It was very helpful for you to inform me about the bug in detail.

I just fixed the bug. 😄
